// <auto-generated />
using DAL_DOTNETCORE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL_DOTNETCORE.Migrations
{
    [DbContext(typeof(PaymentsManagerDBContext))]
    partial class PaymentsManagerDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL_DOTNETCORE.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ReceiverWalletNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SenderWalletNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Time")
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("DAL_DOTNETCORE.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("city")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("country")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("email")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("firstName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("lastName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("passportId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("passwordHash")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tin")
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DAL_DOTNETCORE.Wallet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("walletBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("walletCVV")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("walletDate")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("walletName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("walletNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("walletOwnerPassId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("walletOwnerTIN")
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
